source 'http://rubygems.org'

gem "sinatra"
gem "json"


gem "dm-core"
gem "dm-migrations"

gem "dm-sqlite-adapter"
# gem "dm-mysql-adapter" # or postgres-adapter, for the final version


group :development, :test do
  gem "rspec-core"
  gem "rspec-mocks"
  gem "rspec-expectations"
end